services:
  backend:
    image: exact-backend
    build:
      context: ./platform/backend
    ports:
      - "8000:8000"
    user: root
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/ || kill 1" ]
      interval: 60s
      timeout: 20s
      retries: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./platform/backend:/app
      - ./media:/app/mysite/media
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./platform/frontend
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3000/ > /dev/null || kill 1" ]
      interval: 60s
      timeout: 20s
      retries: 3
    volumes:
      - ./platform/frontend:/app
      - /app/node_modules
    ports:
      - "8080:3000"
    working_dir: /app
    command:
      - sh
      - -c
      - |
        npm run build
        npm start

  # Dieser Dienst ist jetzt AKTIVIERT.
  # Er läuft nicht permanent, aber Docker Compose weiß jetzt, wie man
  # das 'exact-worker'-Image baut, wenn der 'build'-Befehl ausgeführt wird.
  worker:
    build:
      context: ./worker
    image: exact-worker # Wir definieren den Namen des Images explizit
    platform: linux/amd64
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:16
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 60s
      timeout: 10s
      retries: 5

  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - .:/workspaces/exact
    working_dir: /workspaces/exact
    command: sleep infinity
    user: root

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
