# Generated by Django 3.2.23 on 2024-07-10 16:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mlmodel', models.FileField(default='default_mlmodel.txt', upload_to=api.models.challenge_directory_path)),
                ('dataset', models.FileField(default='default_dataset.txt', upload_to=api.models.challenge_directory_path)),
                ('xaimethod', models.FileField(default='default_xaimethod.txt', upload_to=api.models.challenge_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('challenge_id', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
