# Generated by Django 3.2.23 on 2025-06-21 06:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.FileField(blank=True, null=True, upload_to=api.models.dataset_upload_path)),
                ('mlmodel', models.FileField(blank=True, null=True, upload_to=api.models.model_upload_path)),
                ('xaimethod', models.FileField(blank=True, null=True, upload_to=api.models.xai_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('challenge_id', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('method_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
