# Generated by Django 3.2.23 on 2024-06-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='data',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='model',
        ),
        migrations.RemoveField(
            model_name='xaimethod',
            name='xai_method',
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='model_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='xaimethod',
            name='xai_method_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='challenge_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='challenge_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='challenge_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='xaimethod',
            name='challenge_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
