# Generated by Django 3.2.23 on 2026-03-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='emd_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='emd_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='ima_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='ima_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
