# Generated by Django 3.2.23 on 2026-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20260325_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='creator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
