# Generated by Django 3.2.23 on 2024-07-09 16:22

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240611_2237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='Mlmodel',
        ),
        migrations.DeleteModel(
            name='Xaimethod',
        ),
        migrations.AddField(
            model_name='challenge',
            name='dataset',
            field=models.FileField(default='default_dataset.txt', upload_to=api.models.challenge_directory_path),
        ),
        migrations.AddField(
            model_name='challenge',
            name='mlmodel',
            field=models.FileField(default='default_mlmodel.txt', upload_to=api.models.challenge_directory_path),
        ),
        migrations.AddField(
            model_name='challenge',
            name='xaimethod',
            field=models.FileField(default='default_xaimethod.txt', upload_to=api.models.challenge_directory_path),
        ),
        migrations.AddField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='user_id',
            field=models.CharField(default=-1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='challenge_id',
            field=models.CharField(max_length=100),
        ),
    ]
