# Generated by Django 3.2.23 on 2026-05-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_challenge_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='plot_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
